name: python_testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
#    - name: Set up Python 3.10
#      with:
#        python-version: "3.10"
    - name: install dep
      run: pip install pytest
    - name:  run test
      run: pytest


