name: python_testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: master
      with:
        python-version: "3.10"
    - name: install dep
      run: python -m pip install -U pip
            pip install pytest
    - name:  run test
      run: pytest


